//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utfpr.Dados.Worker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utfpr.Dados.API.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório..
        /// </summary>
        internal static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado já existe..
        /// </summary>
        internal static string EmailJahCadastrado {
            get {
                return ResourceManager.GetString("EmailJahCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar usuário..
        /// </summary>
        internal static string ErroAoSalvarUsuario {
            get {
                return ResourceManager.GetString("ErroAoSalvarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro, tente novamente mais tarde..
        /// </summary>
        internal static string ErroInterno {
            get {
                return ResourceManager.GetString("ErroInterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ou senha incorretos.
        /// </summary>
        internal static string LoginOuSenhaIncorretos {
            get {
                return ResourceManager.GetString("LoginOuSenhaIncorretos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objeto de entrada inválido.
        /// </summary>
        internal static string ObjetoEntradaInvalido {
            get {
                return ResourceManager.GetString("ObjetoEntradaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organização não pode ser excluída pois possui vínculo com solicitações de processamento..
        /// </summary>
        internal static string OrganizacaoPossuiVinculoComProcessamentos {
            get {
                return ResourceManager.GetString("OrganizacaoPossuiVinculoComProcessamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um registro com este nome..
        /// </summary>
        internal static string RegistroComNomeJahExistente {
            get {
                return ResourceManager.GetString("RegistroComNomeJahExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não foi encontrado..
        /// </summary>
        internal static string RegistroNaoEncontrado {
            get {
                return ResourceManager.GetString("RegistroNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não foi encontrado..
        /// </summary>
        internal static string RegistroNaoEncontradoGenerico {
            get {
                return ResourceManager.GetString("RegistroNaoEncontradoGenerico", resourceCulture);
            }
        }
    }
}
