version: '3.5'

services:
  backend_postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123Senha4!}
      PGDATA: /data/postgres
    volumes:
       - backend_postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - backend
  
  backend_api:
    container_name: api_container
    build: ./Utfpr.Dados.Api/
    environment:
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
        TOKEN_CONFIGURATION_KEY: ${TOKEN_CONFIGURATION_KEY:-KEY}
        DB_CONNECTION_STRING: "Host=backend_postgres;Port=5432;Database=UTFPR_DADOS;User Id=postgres;Password=123Senha4!;"
    ports:
      - "7036:7036"
    links:
      - backend_postgres
    depends_on:
      - "backend_postgres"
    networks:
      - backend
    
volumes:
    backend_postgres:
    
networks:
    backend:
        driver: bridge