version: '3.5'

services:
  backend-postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123Senha4!}
      PGDATA: /data/postgres
    volumes:
       - backend-postgres-data:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - backend
  
  backend-api:
    container_name: api_container
    build: ./
    environment:
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
        TOKEN_CONFIGURATION_KEY: ${TOKEN_CONFIGURATION_KEY:-KEY}
        DATABASE_URL: "Host=backend_postgres;Port=5432;Database=UTFPR_DADOS;User Id=postgres;Password=123Senha4!;"
        RABBITMQ_CONNECTION_STRING: "amqps://ohwpbhll:lX35CIjzhhNCZxsKGFRfKGhG1uTTLjx4@beaver.rmq.cloudamqp.com/ohwpbhll"
    ports:
      - "7036:7036"
    links:
      - backend-postgres
    depends_on:
      - "backend-postgres"
      - "backend-rabbitmq"
    #  - "backend-worker"
    networks:
      - backend
      
  #backend-worker:
  #  container_name: worker_container
  #  build: ./Utfpr.Dados.Worker/
  #  environment:
  #      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
  #      DATABASE_URL: "Host=backend_postgres;Port=5432;Database=UTFPR_DADOS;User Id=postgres;Password=123Senha4!;"
  #      RABBITMQ_CONNECTION_STRING: "amqps://xvpgyoal:GhYXppTQ1A1RVzVbQfu4H1yjGIlZAuWC@beaver.rmq.cloudamqp.com/xvpgyoal"
  #  depends_on:
  #      - "backend-postgres"
  #      - "backend-rabbitmq"
  #  networks:
  #    - backend
    
  backend-rabbitmq:
    image: rabbitmq
    container_name: rabbit_container
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: a!Bxg6ysb7S!
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - backend-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - backend
     
volumes:
    backend-postgres-data:
    backend-rabbitmq-data:
    
networks:
    backend:
        driver: bridge